version: '3.8'

services:
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix-llm-observability
    ports:
      - "6006:6006"  # Phoenix UI
      - "4317:4317"  # OTLP gRPC endpoint
      - "4318:4318"  # OTLP HTTP endpoint
    environment:
      - PHOENIX_WORKING_DIR=/phoenix
      - PHOENIX_PORT=6006
    volumes:
      - phoenix_data:/phoenix
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL já existe no projeto, mas caso queira um dedicado para Phoenix
  phoenix-db:
    image: postgres:15-alpine
    container_name: phoenix-postgres
    environment:
      POSTGRES_DB: phoenix
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix_secret
    volumes:
      - phoenix_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  phoenix_data:
  phoenix_db: